services:
  frontend:
    build: ./frontend
    ports:
      - "220.132.122.222:3000:3000"  # Bind to the specific IP and port
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - "220.132.122.222:8080:8080"  # Bind to the specific IP and port
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://nodeuser:123456@db:5432/nodedb
    networks:
      - app-network
    volumes:
      - backend_uploads:/app/uploads
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:12
    environment:
      POSTGRES_USER: nodeuser
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: nodedb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  backend_uploads:
