services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    depends_on:
      - backend

  db:
    image: postgres:12
    environment:
      POSTGRES_USER: nodeuser
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: nodedb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://nodeuser:123456@db:5432/nodedb
    networks:
      - app-network
    depends_on:
      - db

  

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
